extraction:
  cpp:
    prepare:
      packages:
        - cmake
        - boost
        - gtest
        - zlib
    configure:
      command:
        - "git clone https://github.com/microsoft/vcpkg"
        - "./vcpkg/bootstrap-vcpkg.sh -disableMetrics"
        - "cd vcpkg"
        - "./vcpkg install boost-iostreams boost-program-options zlib gtest"
    index:
      build_command:
        - "mkdir build && cd build"
        - "cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_TOOLCHAIN_FILE=/opt/src/vcpkg/scripts/buildsystems/vcpkg.cmake ../"
        - "cmake --build ."